
export type DataExchangeApiOptions = {
	name : string
	data : Map<string, any>
}
export interface DataListener {
	listen(name : string, callback : DataExchangeCallback) : void
	removeListener() : void
	removeListenerWithName(name : string) : void
}
export type DataExchangeCallback = (data : Map<string, any>) => void
export type DataExchangeAndroidCallback = (context : any, intent : any) => void
/**
 * 发送数据给原生
 */
export type PostData = (options : DataExchangeApiOptions) => void